--- #YAML:1.0
name: Posy-Plugin-EntryTitles
version: 0.50
author:
  - Kathryn Andersen
abstract: Posy plugin to cache entry titles.
license: perl
requires:
  Posy: 0.9
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::EntryTitles:
    file: lib/Posy/Plugin/EntryTitles.pm
    version: 0.50
generated_by: Module::Build version 0.2607
